export const isLoader = (state): boolean => state.app.loadersCount > 0;
export const isError = (state): boolean => state.app.error;
export const getErrorMessage = (state): string => state.app.errorMessage;
export const isAlert = (state): boolean => state.app.alert;
export const getSuccessMessage = (state): string => state.app.successMessage;
export const getCurrentLocation = (state): number => state.app.currentLocation;
export const isItemsFetched = (state): boolean => state.items.length !== 0;
export const getItems = (state) => state.items;
export const getCategories = (state) => state.categories;
export const getEditProduct = (state) => state.app.editProduct;
export const getLocations = (state) => state.user?.location;
export const isUserFetched = (state): boolean => Object.keys(state.user).length !== 0;
export const getUser = (state) => state.user;
export const getUserId = (state) => state.user?.data?.id || null;
export const isUserWorker = (state): boolean => state.user?.capabilities?.worker || false;
export const isUserLocManager = (state): boolean => state.user?.capabilities?.loc_manager || false;
export const isUserManager = (state): boolean => state.user?.capabilities?.manager || false;
export const isUserAdmin = (state): boolean => state.user?.capabilities?.administrator || false;
export const getInventory = (state) => state.inventory;
export const getReports = (state) => state.reports;
export const isDailyReportsFetched = (state): boolean => Object.keys(state.dailyReports).length !== 0;
export const getDailyReports = (state) => state.dailyReports;
