export const isLoader = (state): boolean => state.app.loadersCount > 0;
export const isError = (state): boolean => state.app.error;
export const getErrorMessage = (state): string => state.app.errorMessage;
export const isAlert = (state): boolean => state.app.alert;
export const getSuccessMessage = (state): boolean => state.app.successMessage;
export const getBookingId = (state): string | null => state.app.bookingId;
export const getBooking = (state): any => state.booking || [];
export const isBookingDataFetched = (state): boolean => state.booking.length !== 0;
export const getBookingOption = (state): any => state.bookingOption || [];
export const isBookingOptionFetched = (state): boolean => Object.keys(state.bookingOption).length !== 0;
export const getHalls = (state): any => state.halls || [];
export const isHallsFetched = (state): boolean => Object.keys(state.halls).length !== 0;
export const getClient = (state): any => state.client || [];
export const getClientId = (state): string => state.booking.client_id;
export const getCurrentStudioId = (state): string => state.booking.hall_id;
export const getClientDeposit100 = (state): string => state.client.deposit100;
export const isClientInfoFetched = (state): boolean => Object.keys(state.client).length !== 0;
export const isContinueOverlapping = (state): boolean => state.booking.continueOverlapping;
export const getContinueOverlappingMessage = (state): string => state.booking.continueOverlappingMessage;
export const isShowCreateNewClientModal = (state): boolean => state.app.showCreateClientModal;
export const getCreateClientContent = (state): any => state.app.createClientContent;
export const isBookingLogsFetched = (state): boolean => state.bookingLogs.length !== 0;
export const getBookingLogs = (state): any => state.bookingLogs;
export const getTransactions = (state): any => state.transactions || [];
export const getTransactionsTotal = (state): Number => state.transactions.total || 0;
export const isTransactionsFetched = (state): boolean => Object.keys(state.transactions).length !== 0;
export const getPrepareClientHours = (state): any => state.app.prepareClientHours;
export const getPackages = (state): any => state.packages;
export const getProducts = (state): any => state.transactions.products;
export const getCartTransaction = (state): any => state.app.cartTransaction;
export const getCartProcessCard = (state): any => state.app.cartProcessCard;
export const getCartSendPaymentLink = (state): any => state.app.cartSendPaymentLink;
export const getStagePermalink = (state): any => state.booking.stagePermalink;
export const getThirdPartyClientIds = (): any => ({
  19339: 'peerspace', 19340: 'storefront', 19341: 'splacer', 51178: 'giggster',
});
export const getBookingStatus = (state): String => state.booking.status;
export const isUserFetched = (state): boolean => Object.keys(state.app.user).length !== 0;
export const getUser = (state): any => state.app.user;
export const getCart = (state): any => state.app.cart;
